[package]
name = "prog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = "0.23", features = ["event-stream"]}
futures = "0.3"
futures-timer = "3.0"
async-std = "1.10"
